backend:
  name: github
  repo: clertonraf/sdd-blog
media_folder: content/assets
public_folder: content/assets
collections:
  - name: blog
    label: Blog
    folder: "content/blog/"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }